const budejie = require('./src/budejie/manager')
const neihanshequ = require('./src/neihanshequ/manager')
const sogou = require('./src/sogou/manager')
const kuaikanshipin = require('./src/kuaikanshipin/manager')


budejie.getTextContents()
// budejie.getImageContents()
// budejie.getVideoContents()
// neihanshequ.getTextContents()
// neihanshequ.getImageContents()
// neihanshequ.getVideoContents()
// sogou.getImageContents()
// sogou.getGifContents()
// sogou.getVideoContents()
// kuaikanshipin.getVideoContents()
